apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: "jobgraphs.ced.io"
spec:
  group: "ced.io"
  version: v1alpha1
  names:
    plural: jobgraphs
    singular: jobgraph
    kind: JobGraph
    listKind: JobGraphList
    shortNames:
      - mtj
  scope: Namespaced
  subresources: {}
  additionalPrinterColumns:
    - name: State
      type: string
      description: State
      JSONPath: .status.state
    - name: Start Time
      type: date
      description: Start Time
      JSONPath: .status.startTime
    - name: End Time
      type: date
      JSONPath: .status.endTime