apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobgraphs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jobgraphs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: jobgraphs
    spec:
      serviceAccountName: jobgraphs
      securityContext:
        fsGroup: 2 #daemon
      containers:
        - name: jobgraphs
          image: carlosdescalzi/jobgraphs:latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
