apiVersion: ced.io/v1alpha1
kind: JobGraph
metadata:
  name: simple-graph
spec:
  graph:
    edges:
      - source: start
        target: task-1
      - source: start
        target: task-2
      - source: start
        target: task-3
      - source: start
        target: task-4
      - source: start
        target: task-5
      - source: start
        target: task-6
      - source: start
        target: task-7
      - source: start
        target: task-8
      - source: task-1 
        target: end
      - source: task-2
        target: end
      - source: task-3
        target: end
      - source: task-4
        target: end
      - source: task-5
        target: end
      - source: task-6
        target: end
      - source: task-7
        target: end
      - source: task-8
        target: end
  jobTemplates:
    - metadata:
        name: start
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-1
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-2
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-3
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-4
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-5
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-6
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-7
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: task-8
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
    - metadata:
        name: end
      spec:
        template:
          spec:
            containers:
              - image: ubuntu:20.04
                command: ["sleep","1"]
            restartPolicy: Never
